workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      node: 20
      npm: true
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Pod install
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_archive.xcarchive
    artifacts:
      - ios_archive.xcarchive
      - $HOME/Library/Developer/Xcode/Archives/**/**/*.ipa
